import type { Metadata } from "next";
import "./globals.css";
import SplashScreen from "@/components/splash-screen";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative">
          <SplashScreen />
          {children}
        </div>
      </body>
    </html>
  );
}
